name: Configure AWS Credentials and Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write  # Allow the workflow to request OIDC tokens
  contents: read   # Allow the workflow to access the repository contents

jobs:
  configure-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::058264181190:role/knactions
          role-session-name: github-actions-session
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0  # Specify the version of Terraform you want to use

      - name: Terraform Init with Migration Check
        run: |
          if terraform init -migrate-state; then
            echo "State migration successful."
          else
            echo "State migration failed. Running without migration."
            terraform init
          fi

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        
#      - name: Terraform Destroy
#        run: terraform destroy -auto-approve        



